$primary = rgb(e4676e)
$surface = rgb(291415)
$secondary = rgb(d6935c)
$error = rgb(fd4663)
$tertiary = rgb(ccc666)
$surface_lowest = rgb(150a0b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
