color0 #1f1c21
color1 #fd4663
color2 #bb67e4
color3 #675cd6
color4 #cc6688
color5 #cf93ec
color6 #9d96e9
color7 #f2f2f3
color8 #6e6574
color9 #fd4663
color10 #bb67e4
color11 #675cd6
color12 #cc6688
color13 #cf93ec
color14 #9d96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1f1c21
background            #1f1c21
foreground            #f2f2f3
selection_foreground  #b4afb6
selection_background  #2a262c
active_border_color   #bb67e4
inactive_border_color #2a262c
url_color             #bb67e4

active_tab_foreground   #211825
active_tab_background   #bb67e4
inactive_tab_foreground #b4afb6
inactive_tab_background #2a262c
cursor_trail_color      #b4afb6
